### ISSUE TITLE
Ability to update acl file without service restart

### ISSUE THREAD

**Issue by mosquito** [daskol/socks-proxy#1]
Hi @daskol fine project. Have you any plans for add ability to reload acl file without restart the service.

I imagine the simplest way to implement it is a handling on SIGHUP signal. Thank you.

**Comment by daskol** [comment]
Sure, I am curretly working on support for GSS API according to [RFC1928](https://tools.ietf.org/html/rfc1928) which is most likely useless. Nevertheless, support for dynamic reload and monitoring have the highest priority.

Thanks for your feedback.
